export * from "./addresses";
export * from "./availability";
export * from "./carts";
export * from "./catalog";
export * from "./enums";
export * from "./events";
export * from "./guest-sessions";
export * from "./images";
export * from "./orders";
export * from "./relations";
export * from "./reviews";
export * from "./role-requests";
export * from "./sellers";
export * from "./supply-agreements";
export * from "./users";

// ─── Inferred types ───────────────────────────────────────────────────────────

import type { addresses } from "./addresses";
import type { availabilityExceptions, availabilityRegular } from "./availability";
import type { carts } from "./carts";
import type { products, productWines, wines } from "./catalog";
import type { eventComments, eventRegistrations, events } from "./events";
import type { guestSessions } from "./guest-sessions";
import type { images } from "./images";
import type { orders } from "./orders";
import type { comments, reviews } from "./reviews";
import type { roleRequests } from "./role-requests";
import type { shops, winemakers } from "./sellers";
import type { supplyAgreements } from "./supply-agreements";
import type { users } from "./users";

export type User = (typeof users)["$inferSelect"];
export type NewUser = (typeof users)["$inferInsert"];
export type Address = (typeof addresses)["$inferSelect"];
export type NewAddress = (typeof addresses)["$inferInsert"];
export type Shop = (typeof shops)["$inferSelect"];
export type Winemaker = (typeof winemakers)["$inferSelect"];
export type Wine = (typeof wines)["$inferSelect"];
export type Product = (typeof products)["$inferSelect"];
export type Order = (typeof orders)["$inferSelect"];
export type Cart = (typeof carts)["$inferSelect"];
export type GuestSession = (typeof guestSessions)["$inferSelect"];
export type RoleRequest = (typeof roleRequests)["$inferSelect"];
export type SupplyAgreement = (typeof supplyAgreements)["$inferSelect"];
export type ProductWine = (typeof productWines)["$inferSelect"];
export type NewProduct = (typeof products)["$inferInsert"];
export type NewProductWine = (typeof productWines)["$inferInsert"];
export type AvailabilityRegular = (typeof availabilityRegular)["$inferSelect"];
export type AvailabilityException = (typeof availabilityExceptions)["$inferSelect"];
export type Event = (typeof events)["$inferSelect"];
export type NewEvent = (typeof events)["$inferInsert"];
export type EventRegistration = (typeof eventRegistrations)["$inferSelect"];
export type EventComment = (typeof eventComments)["$inferSelect"];
export type Review = (typeof reviews)["$inferSelect"];
export type Comment = (typeof comments)["$inferSelect"];
export type Image = (typeof images)["$inferSelect"];
export type NewImage = (typeof images)["$inferInsert"];
