version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
<<<<<<< HEAD
    target-branch: "dev"
    schedule:
      interval: "weekly"
=======
    schedule:
      interval: "weekly"
>>>>>>> origin/main
