/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WinesIndexRouteImport } from './routes/wines/index'
import { Route as WinemakersIndexRouteImport } from './routes/winemakers/index'
import { Route as ShopsIndexRouteImport } from './routes/shops/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as WinesNewRouteImport } from './routes/wines/new'
import { Route as WinemakersNewRouteImport } from './routes/winemakers/new'
import { Route as ShopsNewRouteImport } from './routes/shops/new'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as EventsNewRouteImport } from './routes/events/new'
import { Route as CheckoutConfirmedRouteImport } from './routes/checkout/confirmed'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as WinesIdIndexRouteImport } from './routes/wines/$id/index'
import { Route as WinemakersIdIndexRouteImport } from './routes/winemakers/$id/index'
import { Route as ShopsIdIndexRouteImport } from './routes/shops/$id/index'
import { Route as EventsIdIndexRouteImport } from './routes/events/$id/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as WinesIdImagesRouteImport } from './routes/wines/$id/images'
import { Route as WinesIdEditRouteImport } from './routes/wines/$id/edit'
import { Route as WinemakersIdImagesRouteImport } from './routes/winemakers/$id/images'
import { Route as WinemakersIdEditRouteImport } from './routes/winemakers/$id/edit'
import { Route as ShopsIdSupplyIncomingRouteImport } from './routes/shops/$id/supply-incoming'
import { Route as ShopsIdSupplyBrowseRouteImport } from './routes/shops/$id/supply-browse'
import { Route as ShopsIdOrdersRouteImport } from './routes/shops/$id/orders'
import { Route as ShopsIdInventoryRouteImport } from './routes/shops/$id/inventory'
import { Route as ShopsIdImagesRouteImport } from './routes/shops/$id/images'
import { Route as ShopsIdEditRouteImport } from './routes/shops/$id/edit'
import { Route as ShopsIdAvailabilityRouteImport } from './routes/shops/$id/availability'
import { Route as EventsIdImagesRouteImport } from './routes/events/$id/images'
import { Route as EventsIdEditRouteImport } from './routes/events/$id/edit'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders/$id'
import { Route as AuthenticatedAdminWinemakersRouteImport } from './routes/_authenticated/_admin/winemakers'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated._admin.users'
import { Route as AuthenticatedAdminShopsRouteImport } from './routes/_authenticated/_admin/shops'
import { Route as AuthenticatedAdminRoleRequestsRouteImport } from './routes/_authenticated._admin.role-requests'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/_admin/products'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/_admin/moderation'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated._admin.events'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/_admin/users/index'
import { Route as AuthenticatedAdminRoleRequestsIndexRouteImport } from './routes/_authenticated/_admin/role-requests/index'
import { Route as ShopsIdInventoryNewRouteImport } from './routes/shops/$id/inventory/new'
import { Route as ShopsIdBundlesNewRouteImport } from './routes/shops/$id/bundles/new'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/_admin/users/$id'
import { Route as AuthenticatedAdminRoleRequestsIdRouteImport } from './routes/_authenticated/_admin/role-requests/$id'
import { Route as ShopsIdInventoryProductIdEditRouteImport } from './routes/shops/$id/inventory/$productId/edit'
import { Route as AuthenticatedShop_ownerManageShopsIdRouteImport } from './routes/_authenticated/_shop_owner/manage/shops/$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesIndexRoute = WinesIndexRouteImport.update({
  id: '/wines/',
  path: '/wines/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinemakersIndexRoute = WinemakersIndexRouteImport.update({
  id: '/winemakers/',
  path: '/winemakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesNewRoute = WinesNewRouteImport.update({
  id: '/wines/new',
  path: '/wines/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WinemakersNewRoute = WinemakersNewRouteImport.update({
  id: '/winemakers/new',
  path: '/winemakers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsNewRoute = ShopsNewRouteImport.update({
  id: '/shops/new',
  path: '/shops/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutConfirmedRoute = CheckoutConfirmedRouteImport.update({
  id: '/checkout/confirmed',
  path: '/checkout/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const WinesIdIndexRoute = WinesIdIndexRouteImport.update({
  id: '/wines/$id/',
  path: '/wines/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinemakersIdIndexRoute = WinemakersIdIndexRouteImport.update({
  id: '/winemakers/$id/',
  path: '/winemakers/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdIndexRoute = ShopsIdIndexRouteImport.update({
  id: '/shops/$id/',
  path: '/shops/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdIndexRoute = EventsIdIndexRouteImport.update({
  id: '/events/$id/',
  path: '/events/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const WinesIdImagesRoute = WinesIdImagesRouteImport.update({
  id: '/wines/$id/images',
  path: '/wines/$id/images',
  getParentRoute: () => rootRouteImport,
} as any)
const WinesIdEditRoute = WinesIdEditRouteImport.update({
  id: '/wines/$id/edit',
  path: '/wines/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WinemakersIdImagesRoute = WinemakersIdImagesRouteImport.update({
  id: '/winemakers/$id/images',
  path: '/winemakers/$id/images',
  getParentRoute: () => rootRouteImport,
} as any)
const WinemakersIdEditRoute = WinemakersIdEditRouteImport.update({
  id: '/winemakers/$id/edit',
  path: '/winemakers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdSupplyIncomingRoute = ShopsIdSupplyIncomingRouteImport.update({
  id: '/shops/$id/supply-incoming',
  path: '/shops/$id/supply-incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdSupplyBrowseRoute = ShopsIdSupplyBrowseRouteImport.update({
  id: '/shops/$id/supply-browse',
  path: '/shops/$id/supply-browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdOrdersRoute = ShopsIdOrdersRouteImport.update({
  id: '/shops/$id/orders',
  path: '/shops/$id/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdInventoryRoute = ShopsIdInventoryRouteImport.update({
  id: '/shops/$id/inventory',
  path: '/shops/$id/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdImagesRoute = ShopsIdImagesRouteImport.update({
  id: '/shops/$id/images',
  path: '/shops/$id/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdEditRoute = ShopsIdEditRouteImport.update({
  id: '/shops/$id/edit',
  path: '/shops/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdAvailabilityRoute = ShopsIdAvailabilityRouteImport.update({
  id: '/shops/$id/availability',
  path: '/shops/$id/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdImagesRoute = EventsIdImagesRouteImport.update({
  id: '/events/$id/images',
  path: '/events/$id/images',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdEditRoute = EventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminWinemakersRoute =
  AuthenticatedAdminWinemakersRouteImport.update({
    id: '/winemakers',
    path: '/winemakers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminShopsRoute = AuthenticatedAdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRoleRequestsRoute =
  AuthenticatedAdminRoleRequestsRouteImport.update({
    id: '/role-requests',
    path: '/role-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminRoleRequestsIndexRoute =
  AuthenticatedAdminRoleRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminRoleRequestsRoute,
  } as any)
const ShopsIdInventoryNewRoute = ShopsIdInventoryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShopsIdInventoryRoute,
} as any)
const ShopsIdBundlesNewRoute = ShopsIdBundlesNewRouteImport.update({
  id: '/shops/$id/bundles/new',
  path: '/shops/$id/bundles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminRoleRequestsIdRoute =
  AuthenticatedAdminRoleRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminRoleRequestsRoute,
  } as any)
const ShopsIdInventoryProductIdEditRoute =
  ShopsIdInventoryProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => ShopsIdInventoryRoute,
  } as any)
const AuthenticatedShop_ownerManageShopsIdRoute =
  AuthenticatedShop_ownerManageShopsIdRouteImport.update({
    id: '/_shop_owner/manage/shops/$id',
    path: '/manage/shops/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/search': typeof SearchRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/checkout/confirmed': typeof CheckoutConfirmedRoute
  '/events/new': typeof EventsNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/shops/new': typeof ShopsNewRoute
  '/winemakers/new': typeof WinemakersNewRoute
  '/wines/new': typeof WinesNewRoute
  '/events/': typeof EventsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/winemakers/': typeof WinemakersIndexRoute
  '/wines/': typeof WinesIndexRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/events': typeof AuthenticatedAdminEventsRoute
  '/moderation': typeof AuthenticatedAdminModerationRoute
  '/products': typeof AuthenticatedAdminProductsRoute
  '/role-requests': typeof AuthenticatedAdminRoleRequestsRouteWithChildren
  '/shops': typeof AuthenticatedAdminShopsRoute
  '/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/winemakers': typeof AuthenticatedAdminWinemakersRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/images': typeof EventsIdImagesRoute
  '/shops/$id/availability': typeof ShopsIdAvailabilityRoute
  '/shops/$id/edit': typeof ShopsIdEditRoute
  '/shops/$id/images': typeof ShopsIdImagesRoute
  '/shops/$id/inventory': typeof ShopsIdInventoryRouteWithChildren
  '/shops/$id/orders': typeof ShopsIdOrdersRoute
  '/shops/$id/supply-browse': typeof ShopsIdSupplyBrowseRoute
  '/shops/$id/supply-incoming': typeof ShopsIdSupplyIncomingRoute
  '/winemakers/$id/edit': typeof WinemakersIdEditRoute
  '/winemakers/$id/images': typeof WinemakersIdImagesRoute
  '/wines/$id/edit': typeof WinesIdEditRoute
  '/wines/$id/images': typeof WinesIdImagesRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/shops/$id/': typeof ShopsIdIndexRoute
  '/winemakers/$id/': typeof WinemakersIdIndexRoute
  '/wines/$id/': typeof WinesIdIndexRoute
  '/role-requests/$id': typeof AuthenticatedAdminRoleRequestsIdRoute
  '/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/shops/$id/bundles/new': typeof ShopsIdBundlesNewRoute
  '/shops/$id/inventory/new': typeof ShopsIdInventoryNewRoute
  '/role-requests/': typeof AuthenticatedAdminRoleRequestsIndexRoute
  '/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/manage/shops/$id': typeof AuthenticatedShop_ownerManageShopsIdRoute
  '/shops/$id/inventory/$productId/edit': typeof ShopsIdInventoryProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/search': typeof SearchRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/checkout/confirmed': typeof CheckoutConfirmedRoute
  '/events/new': typeof EventsNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/shops/new': typeof ShopsNewRoute
  '/winemakers/new': typeof WinemakersNewRoute
  '/wines/new': typeof WinesNewRoute
  '/events': typeof AuthenticatedAdminEventsRoute
  '/products': typeof AuthenticatedAdminProductsRoute
  '/shops': typeof AuthenticatedAdminShopsRoute
  '/winemakers': typeof AuthenticatedAdminWinemakersRoute
  '/wines': typeof WinesIndexRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/moderation': typeof AuthenticatedAdminModerationRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/images': typeof EventsIdImagesRoute
  '/shops/$id/availability': typeof ShopsIdAvailabilityRoute
  '/shops/$id/edit': typeof ShopsIdEditRoute
  '/shops/$id/images': typeof ShopsIdImagesRoute
  '/shops/$id/inventory': typeof ShopsIdInventoryRouteWithChildren
  '/shops/$id/orders': typeof ShopsIdOrdersRoute
  '/shops/$id/supply-browse': typeof ShopsIdSupplyBrowseRoute
  '/shops/$id/supply-incoming': typeof ShopsIdSupplyIncomingRoute
  '/winemakers/$id/edit': typeof WinemakersIdEditRoute
  '/winemakers/$id/images': typeof WinemakersIdImagesRoute
  '/wines/$id/edit': typeof WinesIdEditRoute
  '/wines/$id/images': typeof WinesIdImagesRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/events/$id': typeof EventsIdIndexRoute
  '/shops/$id': typeof ShopsIdIndexRoute
  '/winemakers/$id': typeof WinemakersIdIndexRoute
  '/wines/$id': typeof WinesIdIndexRoute
  '/role-requests/$id': typeof AuthenticatedAdminRoleRequestsIdRoute
  '/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/shops/$id/bundles/new': typeof ShopsIdBundlesNewRoute
  '/shops/$id/inventory/new': typeof ShopsIdInventoryNewRoute
  '/role-requests': typeof AuthenticatedAdminRoleRequestsIndexRoute
  '/users': typeof AuthenticatedAdminUsersIndexRoute
  '/manage/shops/$id': typeof AuthenticatedShop_ownerManageShopsIdRoute
  '/shops/$id/inventory/$productId/edit': typeof ShopsIdInventoryProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cart': typeof CartRoute
  '/search': typeof SearchRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/checkout/confirmed': typeof CheckoutConfirmedRoute
  '/events/new': typeof EventsNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/shops/new': typeof ShopsNewRoute
  '/winemakers/new': typeof WinemakersNewRoute
  '/wines/new': typeof WinesNewRoute
  '/events/': typeof EventsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/winemakers/': typeof WinemakersIndexRoute
  '/wines/': typeof WinesIndexRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/_admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/_admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/_admin/role-requests': typeof AuthenticatedAdminRoleRequestsRouteWithChildren
  '/_authenticated/_admin/shops': typeof AuthenticatedAdminShopsRoute
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/_admin/winemakers': typeof AuthenticatedAdminWinemakersRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/images': typeof EventsIdImagesRoute
  '/shops/$id/availability': typeof ShopsIdAvailabilityRoute
  '/shops/$id/edit': typeof ShopsIdEditRoute
  '/shops/$id/images': typeof ShopsIdImagesRoute
  '/shops/$id/inventory': typeof ShopsIdInventoryRouteWithChildren
  '/shops/$id/orders': typeof ShopsIdOrdersRoute
  '/shops/$id/supply-browse': typeof ShopsIdSupplyBrowseRoute
  '/shops/$id/supply-incoming': typeof ShopsIdSupplyIncomingRoute
  '/winemakers/$id/edit': typeof WinemakersIdEditRoute
  '/winemakers/$id/images': typeof WinemakersIdImagesRoute
  '/wines/$id/edit': typeof WinesIdEditRoute
  '/wines/$id/images': typeof WinesIdImagesRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/shops/$id/': typeof ShopsIdIndexRoute
  '/winemakers/$id/': typeof WinemakersIdIndexRoute
  '/wines/$id/': typeof WinesIdIndexRoute
  '/_authenticated/_admin/role-requests/$id': typeof AuthenticatedAdminRoleRequestsIdRoute
  '/_authenticated/_admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/shops/$id/bundles/new': typeof ShopsIdBundlesNewRoute
  '/shops/$id/inventory/new': typeof ShopsIdInventoryNewRoute
  '/_authenticated/_admin/role-requests/': typeof AuthenticatedAdminRoleRequestsIndexRoute
  '/_authenticated/_admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/_shop_owner/manage/shops/$id': typeof AuthenticatedShop_ownerManageShopsIdRoute
  '/shops/$id/inventory/$productId/edit': typeof ShopsIdInventoryProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/search'
    | '/dashboard'
    | '/settings'
    | '/stats'
    | '/auth/login'
    | '/auth/register'
    | '/checkout/confirmed'
    | '/events/new'
    | '/products/$productId'
    | '/shops/new'
    | '/winemakers/new'
    | '/wines/new'
    | '/events/'
    | '/products/'
    | '/shops/'
    | '/winemakers/'
    | '/wines/'
    | '/admin'
    | '/events'
    | '/moderation'
    | '/products'
    | '/role-requests'
    | '/shops'
    | '/users'
    | '/winemakers'
    | '/orders/$id'
    | '/events/$id/edit'
    | '/events/$id/images'
    | '/shops/$id/availability'
    | '/shops/$id/edit'
    | '/shops/$id/images'
    | '/shops/$id/inventory'
    | '/shops/$id/orders'
    | '/shops/$id/supply-browse'
    | '/shops/$id/supply-incoming'
    | '/winemakers/$id/edit'
    | '/winemakers/$id/images'
    | '/wines/$id/edit'
    | '/wines/$id/images'
    | '/orders/'
    | '/events/$id/'
    | '/shops/$id/'
    | '/winemakers/$id/'
    | '/wines/$id/'
    | '/role-requests/$id'
    | '/users/$id'
    | '/shops/$id/bundles/new'
    | '/shops/$id/inventory/new'
    | '/role-requests/'
    | '/users/'
    | '/manage/shops/$id'
    | '/shops/$id/inventory/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/search'
    | '/dashboard'
    | '/settings'
    | '/stats'
    | '/auth/login'
    | '/auth/register'
    | '/checkout/confirmed'
    | '/events/new'
    | '/products/$productId'
    | '/shops/new'
    | '/winemakers/new'
    | '/wines/new'
    | '/events'
    | '/products'
    | '/shops'
    | '/winemakers'
    | '/wines'
    | '/admin'
    | '/moderation'
    | '/orders/$id'
    | '/events/$id/edit'
    | '/events/$id/images'
    | '/shops/$id/availability'
    | '/shops/$id/edit'
    | '/shops/$id/images'
    | '/shops/$id/inventory'
    | '/shops/$id/orders'
    | '/shops/$id/supply-browse'
    | '/shops/$id/supply-incoming'
    | '/winemakers/$id/edit'
    | '/winemakers/$id/images'
    | '/wines/$id/edit'
    | '/wines/$id/images'
    | '/orders'
    | '/events/$id'
    | '/shops/$id'
    | '/winemakers/$id'
    | '/wines/$id'
    | '/role-requests/$id'
    | '/users/$id'
    | '/shops/$id/bundles/new'
    | '/shops/$id/inventory/new'
    | '/role-requests'
    | '/users'
    | '/manage/shops/$id'
    | '/shops/$id/inventory/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cart'
    | '/search'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/stats'
    | '/auth/login'
    | '/auth/register'
    | '/checkout/confirmed'
    | '/events/new'
    | '/products/$productId'
    | '/shops/new'
    | '/winemakers/new'
    | '/wines/new'
    | '/events/'
    | '/products/'
    | '/shops/'
    | '/winemakers/'
    | '/wines/'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/events'
    | '/_authenticated/_admin/moderation'
    | '/_authenticated/_admin/products'
    | '/_authenticated/_admin/role-requests'
    | '/_authenticated/_admin/shops'
    | '/_authenticated/_admin/users'
    | '/_authenticated/_admin/winemakers'
    | '/_authenticated/orders/$id'
    | '/events/$id/edit'
    | '/events/$id/images'
    | '/shops/$id/availability'
    | '/shops/$id/edit'
    | '/shops/$id/images'
    | '/shops/$id/inventory'
    | '/shops/$id/orders'
    | '/shops/$id/supply-browse'
    | '/shops/$id/supply-incoming'
    | '/winemakers/$id/edit'
    | '/winemakers/$id/images'
    | '/wines/$id/edit'
    | '/wines/$id/images'
    | '/_authenticated/orders/'
    | '/events/$id/'
    | '/shops/$id/'
    | '/winemakers/$id/'
    | '/wines/$id/'
    | '/_authenticated/_admin/role-requests/$id'
    | '/_authenticated/_admin/users/$id'
    | '/shops/$id/bundles/new'
    | '/shops/$id/inventory/new'
    | '/_authenticated/_admin/role-requests/'
    | '/_authenticated/_admin/users/'
    | '/_authenticated/_shop_owner/manage/shops/$id'
    | '/shops/$id/inventory/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CartRoute: typeof CartRoute
  SearchRoute: typeof SearchRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CheckoutConfirmedRoute: typeof CheckoutConfirmedRoute
  EventsNewRoute: typeof EventsNewRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ShopsNewRoute: typeof ShopsNewRoute
  WinemakersNewRoute: typeof WinemakersNewRoute
  WinesNewRoute: typeof WinesNewRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  WinemakersIndexRoute: typeof WinemakersIndexRoute
  WinesIndexRoute: typeof WinesIndexRoute
  EventsIdEditRoute: typeof EventsIdEditRoute
  EventsIdImagesRoute: typeof EventsIdImagesRoute
  ShopsIdAvailabilityRoute: typeof ShopsIdAvailabilityRoute
  ShopsIdEditRoute: typeof ShopsIdEditRoute
  ShopsIdImagesRoute: typeof ShopsIdImagesRoute
  ShopsIdInventoryRoute: typeof ShopsIdInventoryRouteWithChildren
  ShopsIdOrdersRoute: typeof ShopsIdOrdersRoute
  ShopsIdSupplyBrowseRoute: typeof ShopsIdSupplyBrowseRoute
  ShopsIdSupplyIncomingRoute: typeof ShopsIdSupplyIncomingRoute
  WinemakersIdEditRoute: typeof WinemakersIdEditRoute
  WinemakersIdImagesRoute: typeof WinemakersIdImagesRoute
  WinesIdEditRoute: typeof WinesIdEditRoute
  WinesIdImagesRoute: typeof WinesIdImagesRoute
  EventsIdIndexRoute: typeof EventsIdIndexRoute
  ShopsIdIndexRoute: typeof ShopsIdIndexRoute
  WinemakersIdIndexRoute: typeof WinemakersIdIndexRoute
  WinesIdIndexRoute: typeof WinesIdIndexRoute
  ShopsIdBundlesNewRoute: typeof ShopsIdBundlesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/': {
      id: '/wines/'
      path: '/wines'
      fullPath: '/wines/'
      preLoaderRoute: typeof WinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winemakers/': {
      id: '/winemakers/'
      path: '/winemakers'
      fullPath: '/winemakers/'
      preLoaderRoute: typeof WinemakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/new': {
      id: '/wines/new'
      path: '/wines/new'
      fullPath: '/wines/new'
      preLoaderRoute: typeof WinesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winemakers/new': {
      id: '/winemakers/new'
      path: '/winemakers/new'
      fullPath: '/winemakers/new'
      preLoaderRoute: typeof WinemakersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/new': {
      id: '/shops/new'
      path: '/shops/new'
      fullPath: '/shops/new'
      preLoaderRoute: typeof ShopsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/confirmed': {
      id: '/checkout/confirmed'
      path: '/checkout/confirmed'
      fullPath: '/checkout/confirmed'
      preLoaderRoute: typeof CheckoutConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/wines/$id/': {
      id: '/wines/$id/'
      path: '/wines/$id'
      fullPath: '/wines/$id/'
      preLoaderRoute: typeof WinesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winemakers/$id/': {
      id: '/winemakers/$id/'
      path: '/winemakers/$id'
      fullPath: '/winemakers/$id/'
      preLoaderRoute: typeof WinemakersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id/': {
      id: '/shops/$id/'
      path: '/shops/$id'
      fullPath: '/shops/$id/'
      preLoaderRoute: typeof ShopsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/': {
      id: '/events/$id/'
      path: '/events/$id'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof EventsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/wines/$id/images': {
      id: '/wines/$id/images'
      path: '/wines/$id/images'
      fullPath: '/wines/$id/images'
      preLoaderRoute: typeof WinesIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wines/$id/edit': {
      id: '/wines/$id/edit'
      path: '/wines/$id/edit'
      fullPath: '/wines/$id/edit'
      preLoaderRoute: typeof WinesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winemakers/$id/images': {
      id: '/winemakers/$id/images'
      path: '/winemakers/$id/images'
      fullPath: '/winemakers/$id/images'
      preLoaderRoute: typeof WinemakersIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winemakers/$id/edit': {
      id: '/winemakers/$id/edit'
      path: '/winemakers/$id/edit'
      fullPath: '/winemakers/$id/edit'
      preLoaderRoute: typeof WinemakersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id/supply-incoming': {
      id: '/shops/$id/supply-incoming'
      path: '/shops/$id/supply-incoming'
      fullPath: '/shops/$id/supply-incoming'
      preLoaderRoute: typeof ShopsIdSupplyIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id/supply-browse': {
      id: '/shops/$id/supply-browse'
      path: '/shops/$id/supply-browse'
      fullPath: '/shops/$id/supply-browse'
      preLoaderRoute: typeof ShopsIdSupplyBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id/orders': {
      id: '/shops/$id/orders'
      path: '/shops/$id/orders'
      fullPath: '/shops/$id/orders'
      preLoaderRoute: typeof ShopsIdOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id/inventory': {
      id: '/shops/$id/inventory'
      path: '/shops/$id/inventory'
      fullPath: '/shops/$id/inventory'
      preLoaderRoute: typeof ShopsIdInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id/images': {
      id: '/shops/$id/images'
      path: '/shops/$id/images'
      fullPath: '/shops/$id/images'
      preLoaderRoute: typeof ShopsIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id/edit': {
      id: '/shops/$id/edit'
      path: '/shops/$id/edit'
      fullPath: '/shops/$id/edit'
      preLoaderRoute: typeof ShopsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id/availability': {
      id: '/shops/$id/availability'
      path: '/shops/$id/availability'
      fullPath: '/shops/$id/availability'
      preLoaderRoute: typeof ShopsIdAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/images': {
      id: '/events/$id/images'
      path: '/events/$id/images'
      fullPath: '/events/$id/images'
      preLoaderRoute: typeof EventsIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/edit': {
      id: '/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof EventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/winemakers': {
      id: '/_authenticated/_admin/winemakers'
      path: '/winemakers'
      fullPath: '/winemakers'
      preLoaderRoute: typeof AuthenticatedAdminWinemakersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/shops': {
      id: '/_authenticated/_admin/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof AuthenticatedAdminShopsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/role-requests': {
      id: '/_authenticated/_admin/role-requests'
      path: '/role-requests'
      fullPath: '/role-requests'
      preLoaderRoute: typeof AuthenticatedAdminRoleRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/products': {
      id: '/_authenticated/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/moderation': {
      id: '/_authenticated/_admin/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/events': {
      id: '/_authenticated/_admin/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/users/': {
      id: '/_authenticated/_admin/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/_admin/role-requests/': {
      id: '/_authenticated/_admin/role-requests/'
      path: '/'
      fullPath: '/role-requests/'
      preLoaderRoute: typeof AuthenticatedAdminRoleRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoleRequestsRoute
    }
    '/shops/$id/inventory/new': {
      id: '/shops/$id/inventory/new'
      path: '/new'
      fullPath: '/shops/$id/inventory/new'
      preLoaderRoute: typeof ShopsIdInventoryNewRouteImport
      parentRoute: typeof ShopsIdInventoryRoute
    }
    '/shops/$id/bundles/new': {
      id: '/shops/$id/bundles/new'
      path: '/shops/$id/bundles/new'
      fullPath: '/shops/$id/bundles/new'
      preLoaderRoute: typeof ShopsIdBundlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/users/$id': {
      id: '/_authenticated/_admin/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/_admin/role-requests/$id': {
      id: '/_authenticated/_admin/role-requests/$id'
      path: '/$id'
      fullPath: '/role-requests/$id'
      preLoaderRoute: typeof AuthenticatedAdminRoleRequestsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoleRequestsRoute
    }
    '/shops/$id/inventory/$productId/edit': {
      id: '/shops/$id/inventory/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/shops/$id/inventory/$productId/edit'
      preLoaderRoute: typeof ShopsIdInventoryProductIdEditRouteImport
      parentRoute: typeof ShopsIdInventoryRoute
    }
    '/_authenticated/_shop_owner/manage/shops/$id': {
      id: '/_authenticated/_shop_owner/manage/shops/$id'
      path: '/manage/shops/$id'
      fullPath: '/manage/shops/$id'
      preLoaderRoute: typeof AuthenticatedShop_ownerManageShopsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRoleRequestsRouteChildren {
  AuthenticatedAdminRoleRequestsIdRoute: typeof AuthenticatedAdminRoleRequestsIdRoute
  AuthenticatedAdminRoleRequestsIndexRoute: typeof AuthenticatedAdminRoleRequestsIndexRoute
}

const AuthenticatedAdminRoleRequestsRouteChildren: AuthenticatedAdminRoleRequestsRouteChildren =
  {
    AuthenticatedAdminRoleRequestsIdRoute:
      AuthenticatedAdminRoleRequestsIdRoute,
    AuthenticatedAdminRoleRequestsIndexRoute:
      AuthenticatedAdminRoleRequestsIndexRoute,
  }

const AuthenticatedAdminRoleRequestsRouteWithChildren =
  AuthenticatedAdminRoleRequestsRoute._addFileChildren(
    AuthenticatedAdminRoleRequestsRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminRoleRequestsRoute: typeof AuthenticatedAdminRoleRequestsRouteWithChildren
  AuthenticatedAdminShopsRoute: typeof AuthenticatedAdminShopsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminWinemakersRoute: typeof AuthenticatedAdminWinemakersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminRoleRequestsRoute:
    AuthenticatedAdminRoleRequestsRouteWithChildren,
  AuthenticatedAdminShopsRoute: AuthenticatedAdminShopsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminWinemakersRoute: AuthenticatedAdminWinemakersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedShop_ownerManageShopsIdRoute: typeof AuthenticatedShop_ownerManageShopsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedShop_ownerManageShopsIdRoute:
    AuthenticatedShop_ownerManageShopsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ShopsIdInventoryRouteChildren {
  ShopsIdInventoryNewRoute: typeof ShopsIdInventoryNewRoute
  ShopsIdInventoryProductIdEditRoute: typeof ShopsIdInventoryProductIdEditRoute
}

const ShopsIdInventoryRouteChildren: ShopsIdInventoryRouteChildren = {
  ShopsIdInventoryNewRoute: ShopsIdInventoryNewRoute,
  ShopsIdInventoryProductIdEditRoute: ShopsIdInventoryProductIdEditRoute,
}

const ShopsIdInventoryRouteWithChildren =
  ShopsIdInventoryRoute._addFileChildren(ShopsIdInventoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CartRoute: CartRoute,
  SearchRoute: SearchRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CheckoutConfirmedRoute: CheckoutConfirmedRoute,
  EventsNewRoute: EventsNewRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ShopsNewRoute: ShopsNewRoute,
  WinemakersNewRoute: WinemakersNewRoute,
  WinesNewRoute: WinesNewRoute,
  EventsIndexRoute: EventsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  WinemakersIndexRoute: WinemakersIndexRoute,
  WinesIndexRoute: WinesIndexRoute,
  EventsIdEditRoute: EventsIdEditRoute,
  EventsIdImagesRoute: EventsIdImagesRoute,
  ShopsIdAvailabilityRoute: ShopsIdAvailabilityRoute,
  ShopsIdEditRoute: ShopsIdEditRoute,
  ShopsIdImagesRoute: ShopsIdImagesRoute,
  ShopsIdInventoryRoute: ShopsIdInventoryRouteWithChildren,
  ShopsIdOrdersRoute: ShopsIdOrdersRoute,
  ShopsIdSupplyBrowseRoute: ShopsIdSupplyBrowseRoute,
  ShopsIdSupplyIncomingRoute: ShopsIdSupplyIncomingRoute,
  WinemakersIdEditRoute: WinemakersIdEditRoute,
  WinemakersIdImagesRoute: WinemakersIdImagesRoute,
  WinesIdEditRoute: WinesIdEditRoute,
  WinesIdImagesRoute: WinesIdImagesRoute,
  EventsIdIndexRoute: EventsIdIndexRoute,
  ShopsIdIndexRoute: ShopsIdIndexRoute,
  WinemakersIdIndexRoute: WinemakersIdIndexRoute,
  WinesIdIndexRoute: WinesIdIndexRoute,
  ShopsIdBundlesNewRoute: ShopsIdBundlesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
