/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinesRouteImport } from './routes/wines'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as WinemakersIdRouteImport } from './routes/winemakers.$id'
import { Route as ShopsIdRouteImport } from './routes/shops.$id'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated.orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedWinemakerRouteImport } from './routes/_authenticated._winemaker'
import { Route as AuthenticatedShop_ownerRouteImport } from './routes/_authenticated._shop_owner'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated._admin'
import { Route as AuthenticatedWinemakerSupplyRouteImport } from './routes/_authenticated._winemaker.supply'
import { Route as AuthenticatedWinemakerManageWinesRouteImport } from './routes/_authenticated._winemaker.manage-wines'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated._admin.users'
import { Route as AuthenticatedAdminRoleRequestsRouteImport } from './routes/_authenticated._admin.role-requests'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated._admin.moderation'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated._admin.admin'
import { Route as AuthenticatedShop_ownerManageShopsIndexRouteImport } from './routes/_authenticated._shop_owner.manage.shops.index'
import { Route as AuthenticatedShop_ownerManageShopsIdRouteImport } from './routes/_authenticated._shop_owner.manage.shops.$id'
import { Route as AuthenticatedShop_ownerManageShopsIdSupplyBrowseRouteImport } from './routes/_authenticated._shop_owner.manage.shops.$id.supply-browse'
import { Route as AuthenticatedShop_ownerManageShopsIdShopOrdersRouteImport } from './routes/_authenticated._shop_owner.manage.shops.$id.shop-orders'
import { Route as AuthenticatedShop_ownerManageShopsIdInventoryRouteImport } from './routes/_authenticated._shop_owner.manage.shops.$id.inventory'
import { Route as AuthenticatedShop_ownerManageShopsIdBundlesRouteImport } from './routes/_authenticated._shop_owner.manage.shops.$id.bundles'

const WinesRoute = WinesRouteImport.update({
  id: '/wines',
  path: '/wines',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopsRoute,
} as any)
const WinemakersIdRoute = WinemakersIdRouteImport.update({
  id: '/winemakers/$id',
  path: '/winemakers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIdRoute = ShopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWinemakerRoute = AuthenticatedWinemakerRouteImport.update({
  id: '/_winemaker',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShop_ownerRoute = AuthenticatedShop_ownerRouteImport.update({
  id: '/_shop_owner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWinemakerSupplyRoute =
  AuthenticatedWinemakerSupplyRouteImport.update({
    id: '/supply',
    path: '/supply',
    getParentRoute: () => AuthenticatedWinemakerRoute,
  } as any)
const AuthenticatedWinemakerManageWinesRoute =
  AuthenticatedWinemakerManageWinesRouteImport.update({
    id: '/manage-wines',
    path: '/manage-wines',
    getParentRoute: () => AuthenticatedWinemakerRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRoleRequestsRoute =
  AuthenticatedAdminRoleRequestsRouteImport.update({
    id: '/role-requests',
    path: '/role-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedShop_ownerManageShopsIndexRoute =
  AuthenticatedShop_ownerManageShopsIndexRouteImport.update({
    id: '/manage/shops/',
    path: '/manage/shops/',
    getParentRoute: () => AuthenticatedShop_ownerRoute,
  } as any)
const AuthenticatedShop_ownerManageShopsIdRoute =
  AuthenticatedShop_ownerManageShopsIdRouteImport.update({
    id: '/manage/shops/$id',
    path: '/manage/shops/$id',
    getParentRoute: () => AuthenticatedShop_ownerRoute,
  } as any)
const AuthenticatedShop_ownerManageShopsIdSupplyBrowseRoute =
  AuthenticatedShop_ownerManageShopsIdSupplyBrowseRouteImport.update({
    id: '/supply-browse',
    path: '/supply-browse',
    getParentRoute: () => AuthenticatedShop_ownerManageShopsIdRoute,
  } as any)
const AuthenticatedShop_ownerManageShopsIdShopOrdersRoute =
  AuthenticatedShop_ownerManageShopsIdShopOrdersRouteImport.update({
    id: '/shop-orders',
    path: '/shop-orders',
    getParentRoute: () => AuthenticatedShop_ownerManageShopsIdRoute,
  } as any)
const AuthenticatedShop_ownerManageShopsIdInventoryRoute =
  AuthenticatedShop_ownerManageShopsIdInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedShop_ownerManageShopsIdRoute,
  } as any)
const AuthenticatedShop_ownerManageShopsIdBundlesRoute =
  AuthenticatedShop_ownerManageShopsIdBundlesRouteImport.update({
    id: '/bundles',
    path: '/bundles',
    getParentRoute: () => AuthenticatedShop_ownerManageShopsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/search': typeof SearchRoute
  '/shops': typeof ShopsRouteWithChildren
  '/wines': typeof WinesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/winemakers/$id': typeof WinemakersIdRoute
  '/shops/': typeof ShopsIndexRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/moderation': typeof AuthenticatedAdminModerationRoute
  '/role-requests': typeof AuthenticatedAdminRoleRequestsRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/manage-wines': typeof AuthenticatedWinemakerManageWinesRoute
  '/supply': typeof AuthenticatedWinemakerSupplyRoute
  '/manage/shops/$id': typeof AuthenticatedShop_ownerManageShopsIdRouteWithChildren
  '/manage/shops/': typeof AuthenticatedShop_ownerManageShopsIndexRoute
  '/manage/shops/$id/bundles': typeof AuthenticatedShop_ownerManageShopsIdBundlesRoute
  '/manage/shops/$id/inventory': typeof AuthenticatedShop_ownerManageShopsIdInventoryRoute
  '/manage/shops/$id/shop-orders': typeof AuthenticatedShop_ownerManageShopsIdShopOrdersRoute
  '/manage/shops/$id/supply-browse': typeof AuthenticatedShop_ownerManageShopsIdSupplyBrowseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/search': typeof SearchRoute
  '/wines': typeof WinesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/winemakers/$id': typeof WinemakersIdRoute
  '/shops': typeof ShopsIndexRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/moderation': typeof AuthenticatedAdminModerationRoute
  '/role-requests': typeof AuthenticatedAdminRoleRequestsRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/manage-wines': typeof AuthenticatedWinemakerManageWinesRoute
  '/supply': typeof AuthenticatedWinemakerSupplyRoute
  '/manage/shops/$id': typeof AuthenticatedShop_ownerManageShopsIdRouteWithChildren
  '/manage/shops': typeof AuthenticatedShop_ownerManageShopsIndexRoute
  '/manage/shops/$id/bundles': typeof AuthenticatedShop_ownerManageShopsIdBundlesRoute
  '/manage/shops/$id/inventory': typeof AuthenticatedShop_ownerManageShopsIdInventoryRoute
  '/manage/shops/$id/shop-orders': typeof AuthenticatedShop_ownerManageShopsIdShopOrdersRoute
  '/manage/shops/$id/supply-browse': typeof AuthenticatedShop_ownerManageShopsIdSupplyBrowseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/search': typeof SearchRoute
  '/shops': typeof ShopsRouteWithChildren
  '/wines': typeof WinesRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_shop_owner': typeof AuthenticatedShop_ownerRouteWithChildren
  '/_authenticated/_winemaker': typeof AuthenticatedWinemakerRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/shops/$id': typeof ShopsIdRoute
  '/winemakers/$id': typeof WinemakersIdRoute
  '/shops/': typeof ShopsIndexRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/_admin/role-requests': typeof AuthenticatedAdminRoleRequestsRoute
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/_winemaker/manage-wines': typeof AuthenticatedWinemakerManageWinesRoute
  '/_authenticated/_winemaker/supply': typeof AuthenticatedWinemakerSupplyRoute
  '/_authenticated/_shop_owner/manage/shops/$id': typeof AuthenticatedShop_ownerManageShopsIdRouteWithChildren
  '/_authenticated/_shop_owner/manage/shops/': typeof AuthenticatedShop_ownerManageShopsIndexRoute
  '/_authenticated/_shop_owner/manage/shops/$id/bundles': typeof AuthenticatedShop_ownerManageShopsIdBundlesRoute
  '/_authenticated/_shop_owner/manage/shops/$id/inventory': typeof AuthenticatedShop_ownerManageShopsIdInventoryRoute
  '/_authenticated/_shop_owner/manage/shops/$id/shop-orders': typeof AuthenticatedShop_ownerManageShopsIdShopOrdersRoute
  '/_authenticated/_shop_owner/manage/shops/$id/supply-browse': typeof AuthenticatedShop_ownerManageShopsIdSupplyBrowseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bundles'
    | '/cart'
    | '/events'
    | '/explore'
    | '/search'
    | '/shops'
    | '/wines'
    | '/dashboard'
    | '/orders'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/shops/$id'
    | '/winemakers/$id'
    | '/shops/'
    | '/admin'
    | '/moderation'
    | '/role-requests'
    | '/users'
    | '/manage-wines'
    | '/supply'
    | '/manage/shops/$id'
    | '/manage/shops/'
    | '/manage/shops/$id/bundles'
    | '/manage/shops/$id/inventory'
    | '/manage/shops/$id/shop-orders'
    | '/manage/shops/$id/supply-browse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bundles'
    | '/cart'
    | '/events'
    | '/explore'
    | '/search'
    | '/wines'
    | '/dashboard'
    | '/orders'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/shops/$id'
    | '/winemakers/$id'
    | '/shops'
    | '/admin'
    | '/moderation'
    | '/role-requests'
    | '/users'
    | '/manage-wines'
    | '/supply'
    | '/manage/shops/$id'
    | '/manage/shops'
    | '/manage/shops/$id/bundles'
    | '/manage/shops/$id/inventory'
    | '/manage/shops/$id/shop-orders'
    | '/manage/shops/$id/supply-browse'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/bundles'
    | '/cart'
    | '/events'
    | '/explore'
    | '/search'
    | '/shops'
    | '/wines'
    | '/_authenticated/_admin'
    | '/_authenticated/_shop_owner'
    | '/_authenticated/_winemaker'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/settings'
    | '/auth/login'
    | '/auth/register'
    | '/products/$productId'
    | '/shops/$id'
    | '/winemakers/$id'
    | '/shops/'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/moderation'
    | '/_authenticated/_admin/role-requests'
    | '/_authenticated/_admin/users'
    | '/_authenticated/_winemaker/manage-wines'
    | '/_authenticated/_winemaker/supply'
    | '/_authenticated/_shop_owner/manage/shops/$id'
    | '/_authenticated/_shop_owner/manage/shops/'
    | '/_authenticated/_shop_owner/manage/shops/$id/bundles'
    | '/_authenticated/_shop_owner/manage/shops/$id/inventory'
    | '/_authenticated/_shop_owner/manage/shops/$id/shop-orders'
    | '/_authenticated/_shop_owner/manage/shops/$id/supply-browse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BundlesRoute: typeof BundlesRoute
  CartRoute: typeof CartRoute
  EventsRoute: typeof EventsRoute
  ExploreRoute: typeof ExploreRoute
  SearchRoute: typeof SearchRoute
  ShopsRoute: typeof ShopsRouteWithChildren
  WinesRoute: typeof WinesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  WinemakersIdRoute: typeof WinemakersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wines': {
      id: '/wines'
      path: '/wines'
      fullPath: '/wines'
      preLoaderRoute: typeof WinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/winemakers/$id': {
      id: '/winemakers/$id'
      path: '/winemakers/$id'
      fullPath: '/winemakers/$id'
      preLoaderRoute: typeof WinemakersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$id': {
      id: '/shops/$id'
      path: '/$id'
      fullPath: '/shops/$id'
      preLoaderRoute: typeof ShopsIdRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_winemaker': {
      id: '/_authenticated/_winemaker'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWinemakerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shop_owner': {
      id: '/_authenticated/_shop_owner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShop_ownerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_winemaker/supply': {
      id: '/_authenticated/_winemaker/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof AuthenticatedWinemakerSupplyRouteImport
      parentRoute: typeof AuthenticatedWinemakerRoute
    }
    '/_authenticated/_winemaker/manage-wines': {
      id: '/_authenticated/_winemaker/manage-wines'
      path: '/manage-wines'
      fullPath: '/manage-wines'
      preLoaderRoute: typeof AuthenticatedWinemakerManageWinesRouteImport
      parentRoute: typeof AuthenticatedWinemakerRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/role-requests': {
      id: '/_authenticated/_admin/role-requests'
      path: '/role-requests'
      fullPath: '/role-requests'
      preLoaderRoute: typeof AuthenticatedAdminRoleRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/moderation': {
      id: '/_authenticated/_admin/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_shop_owner/manage/shops/': {
      id: '/_authenticated/_shop_owner/manage/shops/'
      path: '/manage/shops'
      fullPath: '/manage/shops/'
      preLoaderRoute: typeof AuthenticatedShop_ownerManageShopsIndexRouteImport
      parentRoute: typeof AuthenticatedShop_ownerRoute
    }
    '/_authenticated/_shop_owner/manage/shops/$id': {
      id: '/_authenticated/_shop_owner/manage/shops/$id'
      path: '/manage/shops/$id'
      fullPath: '/manage/shops/$id'
      preLoaderRoute: typeof AuthenticatedShop_ownerManageShopsIdRouteImport
      parentRoute: typeof AuthenticatedShop_ownerRoute
    }
    '/_authenticated/_shop_owner/manage/shops/$id/supply-browse': {
      id: '/_authenticated/_shop_owner/manage/shops/$id/supply-browse'
      path: '/supply-browse'
      fullPath: '/manage/shops/$id/supply-browse'
      preLoaderRoute: typeof AuthenticatedShop_ownerManageShopsIdSupplyBrowseRouteImport
      parentRoute: typeof AuthenticatedShop_ownerManageShopsIdRoute
    }
    '/_authenticated/_shop_owner/manage/shops/$id/shop-orders': {
      id: '/_authenticated/_shop_owner/manage/shops/$id/shop-orders'
      path: '/shop-orders'
      fullPath: '/manage/shops/$id/shop-orders'
      preLoaderRoute: typeof AuthenticatedShop_ownerManageShopsIdShopOrdersRouteImport
      parentRoute: typeof AuthenticatedShop_ownerManageShopsIdRoute
    }
    '/_authenticated/_shop_owner/manage/shops/$id/inventory': {
      id: '/_authenticated/_shop_owner/manage/shops/$id/inventory'
      path: '/inventory'
      fullPath: '/manage/shops/$id/inventory'
      preLoaderRoute: typeof AuthenticatedShop_ownerManageShopsIdInventoryRouteImport
      parentRoute: typeof AuthenticatedShop_ownerManageShopsIdRoute
    }
    '/_authenticated/_shop_owner/manage/shops/$id/bundles': {
      id: '/_authenticated/_shop_owner/manage/shops/$id/bundles'
      path: '/bundles'
      fullPath: '/manage/shops/$id/bundles'
      preLoaderRoute: typeof AuthenticatedShop_ownerManageShopsIdBundlesRouteImport
      parentRoute: typeof AuthenticatedShop_ownerManageShopsIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminRoleRequestsRoute: typeof AuthenticatedAdminRoleRequestsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminRoleRequestsRoute: AuthenticatedAdminRoleRequestsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedShop_ownerManageShopsIdRouteChildren {
  AuthenticatedShop_ownerManageShopsIdBundlesRoute: typeof AuthenticatedShop_ownerManageShopsIdBundlesRoute
  AuthenticatedShop_ownerManageShopsIdInventoryRoute: typeof AuthenticatedShop_ownerManageShopsIdInventoryRoute
  AuthenticatedShop_ownerManageShopsIdShopOrdersRoute: typeof AuthenticatedShop_ownerManageShopsIdShopOrdersRoute
  AuthenticatedShop_ownerManageShopsIdSupplyBrowseRoute: typeof AuthenticatedShop_ownerManageShopsIdSupplyBrowseRoute
}

const AuthenticatedShop_ownerManageShopsIdRouteChildren: AuthenticatedShop_ownerManageShopsIdRouteChildren =
  {
    AuthenticatedShop_ownerManageShopsIdBundlesRoute:
      AuthenticatedShop_ownerManageShopsIdBundlesRoute,
    AuthenticatedShop_ownerManageShopsIdInventoryRoute:
      AuthenticatedShop_ownerManageShopsIdInventoryRoute,
    AuthenticatedShop_ownerManageShopsIdShopOrdersRoute:
      AuthenticatedShop_ownerManageShopsIdShopOrdersRoute,
    AuthenticatedShop_ownerManageShopsIdSupplyBrowseRoute:
      AuthenticatedShop_ownerManageShopsIdSupplyBrowseRoute,
  }

const AuthenticatedShop_ownerManageShopsIdRouteWithChildren =
  AuthenticatedShop_ownerManageShopsIdRoute._addFileChildren(
    AuthenticatedShop_ownerManageShopsIdRouteChildren,
  )

interface AuthenticatedShop_ownerRouteChildren {
  AuthenticatedShop_ownerManageShopsIdRoute: typeof AuthenticatedShop_ownerManageShopsIdRouteWithChildren
  AuthenticatedShop_ownerManageShopsIndexRoute: typeof AuthenticatedShop_ownerManageShopsIndexRoute
}

const AuthenticatedShop_ownerRouteChildren: AuthenticatedShop_ownerRouteChildren =
  {
    AuthenticatedShop_ownerManageShopsIdRoute:
      AuthenticatedShop_ownerManageShopsIdRouteWithChildren,
    AuthenticatedShop_ownerManageShopsIndexRoute:
      AuthenticatedShop_ownerManageShopsIndexRoute,
  }

const AuthenticatedShop_ownerRouteWithChildren =
  AuthenticatedShop_ownerRoute._addFileChildren(
    AuthenticatedShop_ownerRouteChildren,
  )

interface AuthenticatedWinemakerRouteChildren {
  AuthenticatedWinemakerManageWinesRoute: typeof AuthenticatedWinemakerManageWinesRoute
  AuthenticatedWinemakerSupplyRoute: typeof AuthenticatedWinemakerSupplyRoute
}

const AuthenticatedWinemakerRouteChildren: AuthenticatedWinemakerRouteChildren =
  {
    AuthenticatedWinemakerManageWinesRoute:
      AuthenticatedWinemakerManageWinesRoute,
    AuthenticatedWinemakerSupplyRoute: AuthenticatedWinemakerSupplyRoute,
  }

const AuthenticatedWinemakerRouteWithChildren =
  AuthenticatedWinemakerRoute._addFileChildren(
    AuthenticatedWinemakerRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedShop_ownerRoute: typeof AuthenticatedShop_ownerRouteWithChildren
  AuthenticatedWinemakerRoute: typeof AuthenticatedWinemakerRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedShop_ownerRoute: AuthenticatedShop_ownerRouteWithChildren,
  AuthenticatedWinemakerRoute: AuthenticatedWinemakerRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ShopsRouteChildren {
  ShopsIdRoute: typeof ShopsIdRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
}

const ShopsRouteChildren: ShopsRouteChildren = {
  ShopsIdRoute: ShopsIdRoute,
  ShopsIndexRoute: ShopsIndexRoute,
}

const ShopsRouteWithChildren = ShopsRoute._addFileChildren(ShopsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BundlesRoute: BundlesRoute,
  CartRoute: CartRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRoute,
  SearchRoute: SearchRoute,
  ShopsRoute: ShopsRouteWithChildren,
  WinesRoute: WinesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  WinemakersIdRoute: WinemakersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
