// ─────────────────────────────────────────────────────────────────────────────
// Demo seed data file
// DO NOT put logic here. Keys are symbolic — the seed script resolves them to IDs.
// ─────────────────────────────────────────────────────────────────────────────

export type WineData = {
  name: string;
  color: "red" | "white" | "rosé" | "orange" | "gray" | "tawny" | "yellow";
  type: "still" | "sparkling" | "fortified" | "dessert";
  region: string;
  vintageYear: number;
  alcoholContent: string; // e.g. "13.50"
  volumeMl: 375 | 750 | 1500;
  quantity: number;
  attribution: string;
  composition: string;
  description: string; // ← replace with AI content
  basePrice: number; // shops may vary ±15%
  imageUrl?: string; // ← paste your custom wine bottle/label photo URL here
};

export type EventData = {
  name: string;
  description: string; // ← replace with AI content
  isPast: boolean; // true = past event (daysOffset is negative)
  daysOffset: number; // days from seed date (negative = past)
  durationHours: number;
  capacity: number;
  visibility: "public" | "private";
  imageUrl?: string; // ← event banner/venue photo URL
};

export type WinemakerData = {
  key: string;
  ownerKey: "pavlov" | null; // null = fake Clerk account (can't log in)
  email: string;
  name: string;
  description: string; // ← replace with AI content
  phone: string;
  websiteUrl: string;
  city: string;
  imageUrl?: string; // ← winery/vineyard photo URL
  wines: WineData[];
  events: EventData[];
};

export type BundleData = {
  name: string;
  description: string;
  wineNames: string[]; // must match wine names in source winemakers
  price: number;
};

export type ShopData = {
  key: string;
  ownerKey: "boutique" | null; // null = fake Clerk account
  email: string;
  name: string;
  description: string; // ← replace with AI content
  city: string;
  imageUrl?: string; // ← storefront/shop interior photo URL
  sourceWinemakerKeys: string[]; // supply agreements + which wines to list as products
  bundles: BundleData[];
};

// ── Featured users (5 real Clerk accounts — set IDs in .env.local) ────────────
// Required env vars: DEMO_ADMIN_CLERK_ID, DEMO_WINEMAKER_CLERK_ID,
// DEMO_SHOP_OWNER_CLERK_ID, DEMO_CUSTOMER1_CLERK_ID, DEMO_CUSTOMER2_CLERK_ID
export const FEATURED_USERS = {
  admin: {
    email: "admin@winery.demo",
    fname: "Adam",
    lname: "Správce",
    city: "Praha",
  },
  pavlov: {
    email: "pavlov@winery.demo",
    fname: "Jakub",
    lname: "Vinař",
    city: "Pavlov",
  },
  boutique: {
    email: "boutique@winery.demo",
    fname: "Pavel",
    lname: "Obchodník",
    city: "Praha",
  },
  jana: {
    email: "jana@winery.demo",
    fname: "Jana",
    lname: "Zákazníková",
    city: "Praha",
  },
  petr: {
    email: "petr@winery.demo",
    fname: "Petr",
    lname: "Procházka",
    city: "Brno",
  },
} as const;

// ── Supporting customers (fake Clerk IDs — provide data volume) ────────────────
export const SUPPORTING_CUSTOMERS: { fname: string; lname: string; email: string; city: string }[] =
  [
    { fname: "Marie", lname: "Nováková", email: "marie.novakova@demo.cz", city: "Praha" },
    { fname: "Tomáš", lname: "Kovář", email: "tomas.kovar@demo.cz", city: "Brno" },
    { fname: "Eva", lname: "Procházková", email: "eva.prochazkova@demo.cz", city: "Ostrava" },
    { fname: "Lukáš", lname: "Novák", email: "lukas.novak@demo.cz", city: "Plzeň" },
    { fname: "Tereza", lname: "Horáková", email: "tereza.horakova@demo.cz", city: "Olomouc" },
    { fname: "Martin", lname: "Dvořák", email: "martin.dvorak@demo.cz", city: "Liberec" },
    { fname: "Kateřina", lname: "Marková", email: "katerina.markova@demo.cz", city: "Praha" },
    { fname: "Ondřej", lname: "Blažek", email: "ondrej.blazek@demo.cz", city: "Brno" },
    {
      fname: "Petra",
      lname: "Součková",
      email: "petra.souckova@demo.cz",
      city: "České Budějovice",
    },
    {
      fname: "Jiří",
      lname: "Kratochvíl",
      email: "jiri.kratochvil@demo.cz",
      city: "Hradec Králové",
    },
    { fname: "Monika", lname: "Veselá", email: "monika.vesela@demo.cz", city: "Olomouc" },
    { fname: "Radek", lname: "Pospíšil", email: "radek.pospisil@demo.cz", city: "Zlín" },
    { fname: "Simona", lname: "Urbanová", email: "simona.urbanova@demo.cz", city: "Praha" },
    { fname: "Michal", lname: "Šimánek", email: "michal.simanek@demo.cz", city: "Brno" },
    { fname: "Lenka", lname: "Kopecká", email: "lenka.kopecka@demo.cz", city: "Ostrava" },
  ];

// ── Winemakers ────────────────────────────────────────────────────────────────
export const WINEMAKERS: WinemakerData[] = [
  {
    key: "pavlov",
    ownerKey: "pavlov",
    email: "info@vinnesklepypavlov.cz",
    name: "Vinné sklepy Pavlov",
    description:
      "TODO: AI-generate — Mikulov region winery, family-run, specializes in whites from Pálava and Welschriesling grapes. Long history, limestone cellars.",
    phone: "+420 519 430 111",
    websiteUrl: "https://vinnesklepypavlov.cz",
    city: "Pavlov",
    wines: [
      {
        name: "Pálava 2022",
        color: "white",
        type: "still",
        region: "Mikulovská",
        vintageYear: 2022,
        alcoholContent: "13.50",
        volumeMl: 750,
        quantity: 200,
        attribution: "Estate",
        composition: "100% Pálava",
        description: "TODO: AI-generate — aromatic white with peach and rose petal notes.",
        basePrice: 18,
      },
      {
        name: "Welschriesling 2023",
        color: "white",
        type: "still",
        region: "Mikulovská",
        vintageYear: 2023,
        alcoholContent: "12.00",
        volumeMl: 750,
        quantity: 250,
        attribution: "Estate",
        composition: "100% Welschriesling",
        description: "TODO: AI-generate — fresh, crisp white with green apple and citrus.",
        basePrice: 15,
      },
      {
        name: "Müller-Thurgau 2022",
        color: "white",
        type: "still",
        region: "Mikulovská",
        vintageYear: 2022,
        alcoholContent: "11.50",
        volumeMl: 750,
        quantity: 180,
        attribution: "Estate",
        composition: "100% Müller-Thurgau",
        description: "TODO: AI-generate — delicate muscat and citrus peel notes.",
        basePrice: 14,
      },
      {
        name: "Rulandské šedé 2021",
        color: "white",
        type: "still",
        region: "Mikulovská",
        vintageYear: 2021,
        alcoholContent: "14.00",
        volumeMl: 750,
        quantity: 120,
        attribution: "Reserve",
        composition: "100% Rulandské šedé",
        description: "TODO: AI-generate — full-bodied white with pear and vanilla.",
        basePrice: 24,
      },
      {
        name: "Neuburské 2022",
        color: "white",
        type: "still",
        region: "Mikulovská",
        vintageYear: 2022,
        alcoholContent: "13.00",
        volumeMl: 750,
        quantity: 100,
        attribution: "Single Vineyard",
        composition: "100% Neuburské",
        description: "TODO: AI-generate — floral and honey notes, typical varietal character.",
        basePrice: 19,
      },
      {
        name: "Tramín červený 2021",
        color: "white",
        type: "still",
        region: "Mikulovská",
        vintageYear: 2021,
        alcoholContent: "13.50",
        volumeMl: 750,
        quantity: 90,
        attribution: "Estate",
        composition: "100% Tramín červený",
        description: "TODO: AI-generate — intensely aromatic with rose and lychee.",
        basePrice: 22,
      },
      {
        name: "Pálava Sekt 2022",
        color: "white",
        type: "sparkling",
        region: "Mikulovská",
        vintageYear: 2022,
        alcoholContent: "12.00",
        volumeMl: 750,
        quantity: 80,
        attribution: "Estate",
        composition: "100% Pálava",
        description:
          "TODO: AI-generate — elegant sparkling with fine bubbles and fresh grape aroma.",
        basePrice: 32,
      },
      {
        name: "Pálava Výběr z hroznů 2020",
        color: "white",
        type: "still",
        region: "Mikulovská",
        vintageYear: 2020,
        alcoholContent: "14.50",
        volumeMl: 375,
        quantity: 60,
        attribution: "Grand Cru",
        composition: "100% Pálava",
        description:
          "TODO: AI-generate — late harvest, concentrated sweetness with honey and apricot.",
        basePrice: 45,
      },
    ],
    events: [
      {
        name: "Velká degustace Mikulov 2025",
        description:
          "TODO: AI-generate — past flagship tasting event in the historic Pavlov cellars.",
        isPast: true,
        daysOffset: -45,
        durationHours: 3,
        capacity: 40,
        visibility: "public",
      },
      {
        name: "Jaro v Mikulově 2026",
        description:
          "TODO: AI-generate — spring tasting of new vintage releases with vineyard tour.",
        isPast: false,
        daysOffset: 21,
        durationHours: 3,
        capacity: 35,
        visibility: "public",
      },
    ],
  },
  {
    key: "valtice",
    ownerKey: null,
    email: "info@chateauvaltice.cz",
    name: "Chateau Valtice",
    description:
      "TODO: AI-generate — prestigious winery in historic Valtice castle. Premium reds and late harvest specialties.",
    phone: "+420 519 352 422",
    websiteUrl: "https://chateauvaltice.cz",
    city: "Valtice",
    wines: [
      {
        name: "Frankovka 2020",
        color: "red",
        type: "still",
        region: "Velkopavlovická",
        vintageYear: 2020,
        alcoholContent: "13.00",
        volumeMl: 750,
        quantity: 150,
        attribution: "Estate",
        composition: "100% Frankovka",
        description: "TODO: AI-generate — full red with cherry and plum, soft tannins.",
        basePrice: 22,
      },
      {
        name: "Zweigeltrebe 2019",
        color: "red",
        type: "still",
        region: "Velkopavlovická",
        vintageYear: 2019,
        alcoholContent: "13.50",
        volumeMl: 750,
        quantity: 120,
        attribution: "Grand Cru",
        composition: "100% Zweigeltrebe",
        description: "TODO: AI-generate — dark fruit, tobacco and vanilla. Structured tannins.",
        basePrice: 28,
      },
      {
        name: "Cabernet Sauvignon 2019",
        color: "red",
        type: "still",
        region: "Velkopavlovická",
        vintageYear: 2019,
        alcoholContent: "14.00",
        volumeMl: 750,
        quantity: 80,
        attribution: "Grand Cru",
        composition: "100% Cabernet Sauvignon",
        description: "TODO: AI-generate — blackcurrant, cedar and spice with long finish.",
        basePrice: 38,
      },
      {
        name: "Rulandské modré 2018",
        color: "red",
        type: "still",
        region: "Velkopavlovická",
        vintageYear: 2018,
        alcoholContent: "14.50",
        volumeMl: 750,
        quantity: 60,
        attribution: "Reserve",
        composition: "100% Rulandské modré",
        description: "TODO: AI-generate — complex cherry and oak, elegant and balanced.",
        basePrice: 45,
      },
      {
        name: "André 2020",
        color: "red",
        type: "still",
        region: "Velkopavlovická",
        vintageYear: 2020,
        alcoholContent: "13.00",
        volumeMl: 750,
        quantity: 130,
        attribution: "Estate",
        composition: "100% André",
        description: "TODO: AI-generate — Czech variety with dark berry and spice character.",
        basePrice: 20,
      },
      {
        name: "Modrý Portugal 2021",
        color: "red",
        type: "still",
        region: "Velkopavlovická",
        vintageYear: 2021,
        alcoholContent: "12.00",
        volumeMl: 750,
        quantity: 160,
        attribution: "Estate",
        composition: "100% Modrý Portugal",
        description: "TODO: AI-generate — light red with red berry, easy drinking.",
        basePrice: 17,
      },
      {
        name: "Rosé Cuvée 2022",
        color: "rosé",
        type: "still",
        region: "Velkopavlovická",
        vintageYear: 2022,
        alcoholContent: "12.50",
        volumeMl: 750,
        quantity: 140,
        attribution: "Estate",
        composition: "Frankovka, Zweigeltrebe",
        description: "TODO: AI-generate — vibrant strawberry and raspberry, refreshing acidity.",
        basePrice: 20,
      },
      {
        name: "Chateau Cuvée Rouge 2018",
        color: "red",
        type: "still",
        region: "Velkopavlovická",
        vintageYear: 2018,
        alcoholContent: "14.50",
        volumeMl: 750,
        quantity: 40,
        attribution: "Grand Cru",
        composition: "Cabernet Sauvignon, Rulandské modré, Frankovka",
        description: "TODO: AI-generate — flagship blend. Complex, cellar-worthy premium red.",
        basePrice: 65,
      },
    ],
    events: [
      {
        name: "Slavnostní ochutnávka Valtice 2026",
        description: "TODO: AI-generate — premium tasting in the castle cellars, sommelier-guided.",
        isPast: false,
        daysOffset: 35,
        durationHours: 3,
        capacity: 30,
        visibility: "public",
      },
    ],
  },
  {
    key: "znojmo",
    ownerKey: null,
    email: "info@znojmovine.cz",
    name: "Znojemské vinařství",
    description:
      "TODO: AI-generate — Znojmo subregion specialist. Cool-climate whites and Sauvignon Blanc experts.",
    phone: "+420 515 224 300",
    websiteUrl: "https://znojmovine.cz",
    city: "Znojmo",
    wines: [
      {
        name: "Sauvignon 2023",
        color: "white",
        type: "still",
        region: "Znojemská",
        vintageYear: 2023,
        alcoholContent: "12.50",
        volumeMl: 750,
        quantity: 220,
        attribution: "Estate",
        composition: "100% Sauvignon",
        description: "TODO: AI-generate — blackcurrant leaf, nettle and tropical fruit. Vibrant.",
        basePrice: 21,
      },
      {
        name: "Veltlínské zelené 2023",
        color: "white",
        type: "still",
        region: "Znojemská",
        vintageYear: 2023,
        alcoholContent: "12.00",
        volumeMl: 750,
        quantity: 200,
        attribution: "Single Vineyard",
        composition: "100% Veltlínské zelené",
        description: "TODO: AI-generate — pepper, citrus and green herbs. Mineral finish.",
        basePrice: 16,
      },
      {
        name: "Ryzlink vlašský 2022",
        color: "white",
        type: "still",
        region: "Znojemská",
        vintageYear: 2022,
        alcoholContent: "12.00",
        volumeMl: 750,
        quantity: 180,
        attribution: "Estate",
        composition: "100% Ryzlink vlašský",
        description: "TODO: AI-generate — citrus, green apple and mineral. Classic Znojmo style.",
        basePrice: 15,
      },
      {
        name: "Chardonnay 2021",
        color: "white",
        type: "still",
        region: "Znojemská",
        vintageYear: 2021,
        alcoholContent: "13.50",
        volumeMl: 750,
        quantity: 100,
        attribution: "Reserve",
        composition: "100% Chardonnay",
        description: "TODO: AI-generate — buttery with vanilla and toasted oak. Aged in barrique.",
        basePrice: 26,
      },
      {
        name: "Hibernal 2023",
        color: "white",
        type: "still",
        region: "Znojemská",
        vintageYear: 2023,
        alcoholContent: "11.50",
        volumeMl: 750,
        quantity: 140,
        attribution: "Estate",
        composition: "100% Hibernal",
        description:
          "TODO: AI-generate — Czech frost-resistant variety. Fresh with grape and citrus.",
        basePrice: 14,
      },
      {
        name: "Muškát Moravský 2023",
        color: "white",
        type: "still",
        region: "Znojemská",
        vintageYear: 2023,
        alcoholContent: "11.00",
        volumeMl: 750,
        quantity: 120,
        attribution: "Estate",
        composition: "100% Muškát Moravský",
        description: "TODO: AI-generate — intensely aromatic. Perfect aperitif wine.",
        basePrice: 16,
      },
      {
        name: "Sauvignon Pozdní sběr 2021",
        color: "white",
        type: "still",
        region: "Znojemská",
        vintageYear: 2021,
        alcoholContent: "13.00",
        volumeMl: 750,
        quantity: 70,
        attribution: "Single Vineyard",
        composition: "100% Sauvignon",
        description:
          "TODO: AI-generate — late harvest Sauvignon with concentrated tropical character.",
        basePrice: 30,
      },
      {
        name: "Sylvánské zelené 2022",
        color: "white",
        type: "still",
        region: "Znojemská",
        vintageYear: 2022,
        alcoholContent: "11.50",
        volumeMl: 750,
        quantity: 150,
        attribution: "Estate",
        composition: "100% Sylvánské zelené",
        description: "TODO: AI-generate — soft and fruity, apple and pear notes.",
        basePrice: 13,
      },
    ],
    events: [
      {
        name: "Degustace Znojmo 2025",
        description: "TODO: AI-generate — past open cellar day with food pairings.",
        isPast: true,
        daysOffset: -60,
        durationHours: 4,
        capacity: 50,
        visibility: "public",
      },
      {
        name: "Znojemské léto 2026",
        description: "TODO: AI-generate — outdoor summer tasting with local food stalls.",
        isPast: false,
        daysOffset: 42,
        durationHours: 5,
        capacity: 80,
        visibility: "public",
      },
    ],
  },
  {
    key: "modra",
    ownerKey: null,
    email: "info@vinarstvimodra.cz",
    name: "Vinařství Modrá",
    description:
      "TODO: AI-generate — Slovácká subregion. Family estate known for robust reds and aromatic rosé.",
    phone: "+420 572 634 100",
    websiteUrl: "https://vinarstvimodra.cz",
    city: "Uherské Hradiště",
    wines: [
      {
        name: "Regent 2021",
        color: "red",
        type: "still",
        region: "Slovácká",
        vintageYear: 2021,
        alcoholContent: "13.00",
        volumeMl: 750,
        quantity: 160,
        attribution: "Estate",
        composition: "100% Regent",
        description: "TODO: AI-generate — Czech variety. Dark plum and blackberry, medium body.",
        basePrice: 19,
      },
      {
        name: "Dornfelder 2020",
        color: "red",
        type: "still",
        region: "Slovácká",
        vintageYear: 2020,
        alcoholContent: "13.50",
        volumeMl: 750,
        quantity: 120,
        attribution: "Estate",
        composition: "100% Dornfelder",
        description: "TODO: AI-generate — deep colour, rich dark fruit and soft tannins.",
        basePrice: 21,
      },
      {
        name: "Cabernet Moravia 2020",
        color: "red",
        type: "still",
        region: "Slovácká",
        vintageYear: 2020,
        alcoholContent: "13.50",
        volumeMl: 750,
        quantity: 90,
        attribution: "Reserve",
        composition: "100% Cabernet Moravia",
        description: "TODO: AI-generate — Czech Cabernet cross. Herbaceous with dark berry.",
        basePrice: 24,
      },
      {
        name: "Alibernet 2019",
        color: "red",
        type: "still",
        region: "Slovácká",
        vintageYear: 2019,
        alcoholContent: "14.00",
        volumeMl: 750,
        quantity: 70,
        attribution: "Grand Cru",
        composition: "100% Alibernet",
        description: "TODO: AI-generate — concentrated and spicy. Deep violet colour.",
        basePrice: 35,
      },
      {
        name: "Rosé Moravský 2023",
        color: "rosé",
        type: "still",
        region: "Slovácká",
        vintageYear: 2023,
        alcoholContent: "12.00",
        volumeMl: 750,
        quantity: 180,
        attribution: "Estate",
        composition: "Regent, Dornfelder",
        description: "TODO: AI-generate — vibrant rosé with strawberry and watermelon.",
        basePrice: 17,
      },
      {
        name: "Muškát 2023",
        color: "white",
        type: "still",
        region: "Slovácká",
        vintageYear: 2023,
        alcoholContent: "11.00",
        volumeMl: 750,
        quantity: 130,
        attribution: "Estate",
        composition: "100% Muškát Moravský",
        description: "TODO: AI-generate — floral and spicy, natural sweetness.",
        basePrice: 16,
      },
      {
        name: "Cuvée Bílé 2022",
        color: "white",
        type: "still",
        region: "Slovácká",
        vintageYear: 2022,
        alcoholContent: "12.50",
        volumeMl: 750,
        quantity: 110,
        attribution: "Estate",
        composition: "Chardonnay, Muškát, Hibernal",
        description: "TODO: AI-generate — refreshing blend of three whites.",
        basePrice: 18,
      },
      {
        name: "Cuvée Červené Grand Cru 2018",
        color: "red",
        type: "still",
        region: "Slovácká",
        vintageYear: 2018,
        alcoholContent: "14.50",
        volumeMl: 750,
        quantity: 35,
        attribution: "Grand Cru",
        composition: "Alibernet, Cabernet Moravia, Dornfelder",
        description: "TODO: AI-generate — flagship red cuvée. Complex, cellar-worthy.",
        basePrice: 55,
      },
    ],
    events: [
      {
        name: "Slovácká ochutnávka 2026",
        description: "TODO: AI-generate — folk music themed tasting event with regional cuisine.",
        isPast: false,
        daysOffset: 56,
        durationHours: 4,
        capacity: 60,
        visibility: "public",
      },
    ],
  },
  {
    key: "bohemia",
    ownerKey: null,
    email: "info@vinarstvibohemia.cz",
    name: "Vinařství Čechy",
    description:
      "TODO: AI-generate — Northern Bohemia pioneer. Cool-climate wines from Mělník and surrounding areas.",
    phone: "+420 315 622 100",
    websiteUrl: "https://vinarstvibohemia.cz",
    city: "Mělník",
    wines: [
      {
        name: "Riesling 2022",
        color: "white",
        type: "still",
        region: "Čechy",
        vintageYear: 2022,
        alcoholContent: "11.50",
        volumeMl: 750,
        quantity: 150,
        attribution: "Estate",
        composition: "100% Riesling",
        description: "TODO: AI-generate — classic Riesling with lime, slate mineral notes.",
        basePrice: 18,
      },
      {
        name: "Hibernal 2023",
        color: "white",
        type: "still",
        region: "Čechy",
        vintageYear: 2023,
        alcoholContent: "11.00",
        volumeMl: 750,
        quantity: 120,
        attribution: "Estate",
        composition: "100% Hibernal",
        description:
          "TODO: AI-generate — fresh and aromatic. Excellent frost-resistant Czech variety.",
        basePrice: 14,
      },
      {
        name: "Müller-Thurgau 2022",
        color: "white",
        type: "still",
        region: "Čechy",
        vintageYear: 2022,
        alcoholContent: "11.00",
        volumeMl: 750,
        quantity: 180,
        attribution: "Estate",
        composition: "100% Müller-Thurgau",
        description: "TODO: AI-generate — light with muscat and citrus. Great summer wine.",
        basePrice: 13,
      },
      {
        name: "Pinot Noir 2021",
        color: "red",
        type: "still",
        region: "Čechy",
        vintageYear: 2021,
        alcoholContent: "12.50",
        volumeMl: 750,
        quantity: 90,
        attribution: "Reserve",
        composition: "100% Pinot Noir",
        description: "TODO: AI-generate — delicate red with cherry and forest floor notes.",
        basePrice: 28,
      },
      {
        name: "Solaris 2022",
        color: "white",
        type: "still",
        region: "Čechy",
        vintageYear: 2022,
        alcoholContent: "12.00",
        volumeMl: 750,
        quantity: 100,
        attribution: "Estate",
        composition: "100% Solaris",
        description: "TODO: AI-generate — disease-resistant variety. Tropical fruit and spice.",
        basePrice: 16,
      },
      {
        name: "Tramín červený 2022",
        color: "white",
        type: "still",
        region: "Čechy",
        vintageYear: 2022,
        alcoholContent: "13.00",
        volumeMl: 750,
        quantity: 80,
        attribution: "Single Vineyard",
        composition: "100% Tramín červený",
        description: "TODO: AI-generate — aromatic rose petal and lychee from Bohemia.",
        basePrice: 22,
      },
      {
        name: "Cabernet Cortis 2021",
        color: "red",
        type: "still",
        region: "Čechy",
        vintageYear: 2021,
        alcoholContent: "12.50",
        volumeMl: 750,
        quantity: 70,
        attribution: "Estate",
        composition: "100% Cabernet Cortis",
        description: "TODO: AI-generate — frost-hardy red variety. Dark fruit and herbal notes.",
        basePrice: 20,
      },
      {
        name: "Mělnické Cuvée 2020",
        color: "red",
        type: "still",
        region: "Čechy",
        vintageYear: 2020,
        alcoholContent: "13.00",
        volumeMl: 750,
        quantity: 60,
        attribution: "Reserve",
        composition: "Pinot Noir, Cabernet Cortis",
        description:
          "TODO: AI-generate — signature Mělník blend. Elegant with good ageing potential.",
        basePrice: 32,
      },
    ],
    events: [
      {
        name: "Bohemian Wine Experience 2026",
        description: "TODO: AI-generate — showcase of northern Bohemia's best, riverside setting.",
        isPast: false,
        daysOffset: 63,
        durationHours: 4,
        capacity: 45,
        visibility: "public",
      },
    ],
  },
  {
    key: "slavia",
    ownerKey: null,
    email: "info@vinarstvislavia.cz",
    name: "Vinařství Slavia",
    description:
      "TODO: AI-generate — Mělník estate with royal heritage. Specializes in Ludmila and St. Václav varieties.",
    phone: "+420 315 622 200",
    websiteUrl: "https://vinarstvislavia.cz",
    city: "Mělník",
    wines: [
      {
        name: "Ludmila 2022",
        color: "red",
        type: "still",
        region: "Čechy",
        vintageYear: 2022,
        alcoholContent: "12.50",
        volumeMl: 750,
        quantity: 130,
        attribution: "Estate",
        composition: "100% Ludmila",
        description: "TODO: AI-generate — historic Czech variety. Red berry and earthy character.",
        basePrice: 20,
      },
      {
        name: "Svatovavřinecké 2021",
        color: "red",
        type: "still",
        region: "Čechy",
        vintageYear: 2021,
        alcoholContent: "12.00",
        volumeMl: 750,
        quantity: 150,
        attribution: "Estate",
        composition: "100% Svatovavřinecké",
        description: "TODO: AI-generate — traditional Czech red. Light body with cherry and spice.",
        basePrice: 17,
      },
      {
        name: "Mělnické Červené 2022",
        color: "red",
        type: "still",
        region: "Čechy",
        vintageYear: 2022,
        alcoholContent: "12.50",
        volumeMl: 750,
        quantity: 160,
        attribution: "Estate",
        composition: "Ludmila, Svatovavřinecké",
        description: "TODO: AI-generate — Mělník signature blend. Accessible and food-friendly.",
        basePrice: 18,
      },
      {
        name: "Chardonnay 2022",
        color: "white",
        type: "still",
        region: "Čechy",
        vintageYear: 2022,
        alcoholContent: "13.00",
        volumeMl: 750,
        quantity: 100,
        attribution: "Reserve",
        composition: "100% Chardonnay",
        description: "TODO: AI-generate — barrel-aged Chardonnay with buttery texture.",
        basePrice: 24,
      },
      {
        name: "Rulandské šedé 2021",
        color: "white",
        type: "still",
        region: "Čechy",
        vintageYear: 2021,
        alcoholContent: "13.50",
        volumeMl: 750,
        quantity: 80,
        attribution: "Single Vineyard",
        composition: "100% Rulandské šedé",
        description: "TODO: AI-generate — rich and textured from Bohemian terroir.",
        basePrice: 26,
      },
      {
        name: "Riesling 2022",
        color: "white",
        type: "still",
        region: "Čechy",
        vintageYear: 2022,
        alcoholContent: "11.50",
        volumeMl: 750,
        quantity: 120,
        attribution: "Estate",
        composition: "100% Riesling",
        description: "TODO: AI-generate — crisp and mineral, citrus-driven.",
        basePrice: 17,
      },
      {
        name: "Rosé Slavia 2023",
        color: "rosé",
        type: "still",
        region: "Čechy",
        vintageYear: 2023,
        alcoholContent: "12.00",
        volumeMl: 750,
        quantity: 140,
        attribution: "Estate",
        composition: "Ludmila, Rulandské modré",
        description: "TODO: AI-generate — delicate pink with strawberry and rose water.",
        basePrice: 18,
      },
      {
        name: "Hradní Cuvée 2019",
        color: "red",
        type: "still",
        region: "Čechy",
        vintageYear: 2019,
        alcoholContent: "13.50",
        volumeMl: 750,
        quantity: 40,
        attribution: "Grand Cru",
        composition: "Ludmila, Svatovavřinecké, Cabernet Cortis",
        description:
          "TODO: AI-generate — castle flagship. Complex, earthy, outstanding ageing potential.",
        basePrice: 48,
      },
    ],
    events: [
      {
        name: "Slavnostní večer Slavia 2025",
        description: "TODO: AI-generate — past gala tasting evening at the castle with live music.",
        isPast: true,
        daysOffset: -30,
        durationHours: 4,
        capacity: 50,
        visibility: "public",
      },
      {
        name: "Mělník Open Cellar 2026",
        description:
          "TODO: AI-generate — public open cellar day, self-guided tasting with winemaker Q&A.",
        isPast: false,
        daysOffset: 49,
        durationHours: 6,
        capacity: 100,
        visibility: "public",
      },
    ],
  },
];

// ── Shops ─────────────────────────────────────────────────────────────────────
export const SHOPS: ShopData[] = [
  {
    key: "boutique",
    ownerKey: "boutique",
    email: "info@prahawine.cz",
    name: "Praha Wine Boutique",
    description:
      "TODO: AI-generate — premium wine shop in Prague city centre. Curated selection of Moravian whites and premium reds.",
    city: "Praha",
    sourceWinemakerKeys: ["pavlov", "valtice"],
    bundles: [
      {
        name: "Moravská bílá kolekce",
        description: "Curated selection of three Moravian whites from Pavlov.",
        wineNames: ["Pálava 2022", "Welschriesling 2023", "Rulandské šedé 2021"],
        price: 52,
      },
      {
        name: "Prémiová červená kolekce",
        description: "Three premium reds from Chateau Valtice.",
        wineNames: ["Frankovka 2020", "Cabernet Sauvignon 2019", "Chateau Cuvée Rouge 2018"],
        price: 120,
      },
    ],
  },
  {
    key: "brno",
    ownerKey: null,
    email: "info@vinarnabrno.cz",
    name: "Vinárna Brno",
    description:
      "TODO: AI-generate — cosy wine bar and bottle shop in Brno city centre. Local wines and monthly tastings.",
    city: "Brno",
    sourceWinemakerKeys: ["valtice", "znojmo"],
    bundles: [
      {
        name: "Znojemský výběr",
        description: "Three whites from Znojmo subregion.",
        wineNames: ["Sauvignon 2023", "Veltlínské zelené 2023", "Ryzlink vlašský 2022"],
        price: 48,
      },
    ],
  },
  {
    key: "olomouc",
    ownerKey: null,
    email: "info@vinotekaolomouc.cz",
    name: "Vinotéka Olomouc",
    description:
      "TODO: AI-generate — Olomouc specialty wine shop with focus on Znojmo and Slovácká subregions.",
    city: "Olomouc",
    sourceWinemakerKeys: ["znojmo", "modra"],
    bundles: [],
  },
  {
    key: "ostrava",
    ownerKey: null,
    email: "info@vinoostrava.cz",
    name: "Víno Ostrava",
    description:
      "TODO: AI-generate — Ostrava wine merchant specializing in robust Moravian reds and rosé.",
    city: "Ostrava",
    sourceWinemakerKeys: ["modra", "bohemia"],
    bundles: [
      {
        name: "Slovácká červená kolekce",
        description: "Top reds from the Slovácká subregion.",
        wineNames: ["Regent 2021", "Dornfelder 2020", "Alibernet 2019"],
        price: 72,
      },
    ],
  },
  {
    key: "liberec",
    ownerKey: null,
    email: "info@vinarnalib.cz",
    name: "Severočeská Vinotéka",
    description:
      "TODO: AI-generate — Northern Bohemia specialist. The only shop focused on Czech-grown wines from Bohemia.",
    city: "Liberec",
    sourceWinemakerKeys: ["bohemia", "slavia"],
    bundles: [
      {
        name: "Bohemian Collection",
        description: "Three wines celebrating northern Bohemian terroir.",
        wineNames: ["Riesling 2022", "Pinot Noir 2021", "Mělnické Cuvée 2020"],
        price: 75,
      },
    ],
  },
];

// ── Curated story interactions ────────────────────────────────────────────────
// These define the "hero" demo flows for featured customers.

export const STORY = {
  // Jana: Praha customer, orders from boutique, active reviewer
  jana: {
    orders: [
      {
        shopKey: "boutique",
        status: "delivered" as const,
        items: [
          { wineName: "Pálava 2022", winemakerId: "pavlov", quantity: 2 },
          { wineName: "Rulandské šedé 2021", winemakerId: "pavlov", quantity: 1 },
          { wineName: "Chateau Cuvée Rouge 2018", winemakerId: "valtice", quantity: 1 },
        ],
      },
      {
        shopKey: "boutique",
        status: "confirmed" as const,
        items: [{ wineName: "Pálava Sekt 2022", winemakerId: "pavlov", quantity: 3 }],
      },
    ],
    productReviews: [
      {
        wineName: "Pálava 2022",
        winemakerId: "pavlov",
        shopKey: "boutique",
        rating: 5,
        body: "TODO: AI-generate — glowing review of Pálava 2022 from a satisfied customer.",
      },
      {
        wineName: "Chateau Cuvée Rouge 2018",
        winemakerId: "valtice",
        shopKey: "boutique",
        rating: 5,
        body: "TODO: AI-generate — enthusiastic review of the flagship red cuvée.",
      },
      {
        wineName: "Rulandské šedé 2021",
        winemakerId: "pavlov",
        shopKey: "boutique",
        rating: 4,
        body: "TODO: AI-generate — positive review of Rulandské šedé with a minor note.",
      },
    ],
    winemakerReviews: [
      {
        winemakerId: "pavlov",
        rating: 5,
        body: "TODO: AI-generate — Jana's review of Vinné sklepy Pavlov as a winemaker.",
      },
    ],
    eventRegistrations: ["pavlov-0", "valtice-0"], // event keys: "{winemakerKey}-{eventIndex}"
  },

  // Petr: Brno customer, one order, one winemaker review
  petr: {
    orders: [
      {
        shopKey: "brno",
        status: "delivered" as const,
        items: [
          { wineName: "Frankovka 2020", winemakerId: "valtice", quantity: 2 },
          { wineName: "Sauvignon 2023", winemakerId: "znojmo", quantity: 2 },
        ],
      },
    ],
    productReviews: [
      {
        wineName: "Frankovka 2020",
        winemakerId: "valtice",
        shopKey: "brno",
        rating: 4,
        body: "TODO: AI-generate — Petr's review of Frankovka from Valtice.",
      },
    ],
    winemakerReviews: [
      {
        winemakerId: "valtice",
        rating: 4,
        body: "TODO: AI-generate — Petr's review of Chateau Valtice as a winemaker.",
      },
    ],
    eventRegistrations: ["znojmo-1", "slavia-1"],
  },
};

// ── Review content for supporting customers ────────────────────────────────────
// Script picks randomly from these for fake customer reviews.
export const REVIEW_BODIES = {
  positive: [
    "TODO: AI-generate — positive review body 1",
    "TODO: AI-generate — positive review body 2",
    "TODO: AI-generate — positive review body 3",
    "TODO: AI-generate — positive review body 4",
    "TODO: AI-generate — positive review body 5",
    "TODO: AI-generate — positive review body 6",
    "TODO: AI-generate — positive review body 7",
    "TODO: AI-generate — positive review body 8",
  ],
  neutral: [
    "TODO: AI-generate — neutral/mixed review body 1",
    "TODO: AI-generate — neutral/mixed review body 2",
    "TODO: AI-generate — neutral/mixed review body 3",
    "TODO: AI-generate — neutral/mixed review body 4",
  ],
  critical: [
    "TODO: AI-generate — critical but fair review body 1",
    "TODO: AI-generate — critical but fair review body 2",
  ],
};

export const EVENT_COMMENT_BODIES = [
  "TODO: AI-generate — event comment 1 (excited attendee)",
  "TODO: AI-generate — event comment 2 (asking about parking)",
  "TODO: AI-generate — event comment 3 (recommending to friend)",
  "TODO: AI-generate — event comment 4 (asking about food)",
  "TODO: AI-generate — event comment 5 (positive feedback after event)",
  "TODO: AI-generate — event comment 6 (follow-up question)",
  "TODO: AI-generate — event comment 7 (first-time attendee excited)",
  "TODO: AI-generate — event comment 8 (reviewing the event)",
];
